language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - /home/travis/.cache/firebase/emulators
before_script:
  - "npm install -g firebase-tools"
  - "cd functions && npm install && cd .."
script:
  #disable using CI env variable
  - "CI=false"
  #remember to use "chmod +x (your_shell_script)" to change permission of your shell script
  - firebase emulators:exec ./integration-test.sh
  #- "npm run test"
  - "npm run build"

after_failure:
  - "cat /home/travis/.npm/_logs/*.log"
#Now we use netlify for deployment
# deploy:
#   provider: netlify
#   cleanup: true
#   site: Triplaned
#   # github_token: $TripPlanner_Github_Token
#   auth: $Triplaned_Netlify_Token
#   # local_dir: build
#   dir: ".next"
#   edge: false
#   on:
#     branch: Netlify